# Generated by Django 2.2.1 on 2019-05-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPaper',
        ),
    ]
